# Generated by Django 2.2.12 on 2020-06-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrequentlyAskedQuestions',
            fields=[
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('shaid', models.CharField(max_length=512, primary_key=True, serialize=False)),
            ],
        ),
    ]
